bind: 0.0.0.0:9000
threads: 5
servers:
  cpai:
    host: 10.0.10.12
    port: 32168
pipelines:
  delivery:
    type: object
    server: cpai
    model: ipcam-general
    threshold: 0.8
    filter: '.label == "car"'
  face:
    type: face_detect
    server: cpai
    threshold: 0.8
    filter: '.label == "person"'
  recognize:
    type: face_recognize
    server: cpai
    threshold: 0.8
    filter: '.label == "person"'
topics:
  - subscribe: frigate/events
    pipeline: delivery
    filter: '.label == "car"'
  - subscribe: frigate/events
    pipeline:
      - face
      - recognize
    filter: '.label == "person"'
frigate: http://10.0.12.66:5000