ATTR_BIND = "bind"
ATTR_BIND_IP = "ip"
ATTR_BIND_PORT = "port"

ATTR_FRIGATE = "frigate"
ATTR_FRIGATE_HOST = "host"
ATTR_FRIGATE_PORT = "port"

ATTR_THREADS = "threads"

ATTR_SERVERS = "servers"
ATTR_SERVER_HOST = "host"
ATTR_SERVER_PORT = "port"

ATTR_PIPELINES = "pipelines"
ATTR_PIPELINE_SERVER = "server"
ATTR_PIPELINE_MODEL = "model"
ATTR_PIPELINE_THRESHOLD = "threshold"
ATTR_PIPELINE_RESULT_TOPIC = "result_topic"
ATTR_PIPELINE_FILTER = "filter"
ATTR_PIPELINE_TYPE = "type"

PIPELINE_FACE_DETECT = "face_detect"
PIPELINE_FACE_RECOGNIZE = "face_recognize"
PIPELINE_OBJECT = "object"
PIPELINE_VISION = "vision"

ATTR_TOPICS = "topics"
ATTR_TOPIC_TOPIC = "subscribe"
ATTR_TOPIC_PIPELINE = "pipeline"
